/**
 * 389. Find the Difference
Easy
Topics
premium lock icon
Companies
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
// COMMENT t.length == s.length + 1
s and t consist of lowercase English letters.

 */

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference1 = function (s, t) {
	let sum1 = 0;
	let sum2 = 0
	for(let i = 0; i < s.length; i++){
		sum1 += s[i].charCodeAt(0)
	}

	for (let i = 0; i < t.length; i++) {
		sum2 += t[i].charCodeAt(0)
	}
	return sum1 > sum2 ? String.fromCharCode(sum1- sum2) : String.fromCharCode(sum2 - sum1);
};

var findTheDifference = function (s, t) {
	let charMap = new Map()
	for (let i = 0; i < s.length; i++) {
		charMap.set(s[i], (charMap.get(s[i]) || 0) + 1)
	}

	for (let i = 0; i < t.length; i++) {
		if (!charMap.has(t[i]) || charMap.get(t[i]) == 0 ) return t[i];
		charMap.set(t[i], charMap.get(t[i]) - 1)
	}
};

const char = findTheDifference('', 'y')
// const char = findTheDifference('abcd', 'abcde')
console.log(char)